server:
  port: 9091

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mi-grupo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema:
          registry:
            url: http://127.0.0.1:8081
        specific:
          avro:
            reader: "true"

topic:
  name: 'mi-topic'